### ISSUE TITLE
Calculation of AMV

### ISSUE THREAD

**Issue by hilbert9221** [abduallahmohamed/Social-Implicit#14]
Thanks for providing the implementations of AMD and AMV.

I am confused by the code about AMV when taking the average. In the function `calc_amd_amv` of the file `amd_amv_kde_metrics.py`, the estimated covariance matrix is averaged over all time steps and all agents. Then, the maximum eigenvalue is computed on the averaged matrix. The calculation is inconsistent with Eq. (4) in the paper. Eq. (4) says the covariance matrix is estimated for each agent at each time step, from which a maximum eigenvalue is computed. The final AMV is obtained by averaging these eigen values. I belive the two quanties, i.e., *maximum eigen value of an average matrix* and *the average of maximum eigen values*, are generally not equal.

Could you explain the difference? It will be valuable for me when applying the code to new predictions on other datasets.

**Comment by abduallahmohamed** [comment]
Hi Chen,

Thanks for highlighting this. The short answer for the moment, the code is
the ground truth for the AMV. It might be the case that it was miss
represented in the text.
I strongly think the code is the correct one as it aligns with the expected
visualization. When designing the AMV I wanted it to act as ADE/FDE in a
sense.
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
