### ISSUE TITLE
About Visualization in papers

### ISSUE THREAD

**Issue by kunhub9** [abduallahmohamed/Social-Implicit#4]
Thank you very much for your great contribution. I am very interested in the results of model visualization in your paper. I want to visualize my model. What should I do?

**Comment by abduallahmohamed** [comment]
Hi, 
Match the output format of your code with ours and use the visualization notebooks provided

**Comment by kunhub9** [comment]
> Hi, Match the output format of your code with ours and use the visualization notebooks provided

Thank you for your reply. I will try it.
