### ISSUE TITLE
Problem about visualization data.

### ISSUE THREAD

**Issue by Shawnjx** [abduallahmohamed/Social-Implicit#6]
Great work! Thank you for contributing the code. I am now trying to make a visualization following the provided code. But when I run the Align.ipynb, the return value in sections 4 to 7 are (181, 181, 364, 181) instead of (2253, 2253, 2356, 2253). But section 3 (Trajectorn++) returns the same value as 364. Is there any problem with my package version or the downloaded data? 
![Screenshot from 2022-10-08 09-20-33](https://user-images.githubusercontent.com/23427669/194680561-7216743e-6815-4a19-9e32-cfbbd394ea17.png)

**Comment by Shawnjx** [comment]
Also, the plotting is kind of weird. 
![case_eth_0](https://user-images.githubusercontent.com/23427669/194792981-61d7b959-93e2-48da-8dbf-1efbb7ccced1.png)

**Comment by abduallahmohamed** [comment]
Hello, 

Thanks for your interest in our work. I've updated the visualization scripts. 
The numbers 181,181,364,181 are indeed correct. The other numbers where from an old run of the script.These numbers where a duplications and was cleaned. 
The Align.ipynb has been updated and you can run it directly. 
The visualization.ipynb and the zoomed version has been updated too. 
Please let me know if there is any issues.

**Comment by Shawnjx** [comment]
Really appreciate your help. I download the new version of the Visualization file. The code is running perfectly now.
![case_eth_95](https://user-images.githubusercontent.com/23427669/194988466-d6c06056-792e-4958-9813-e6bf83d5f9ef.png)
