### ISSUE TITLE
How to evaluate AMD/AMV for the other models?

### ISSUE THREAD

**Issue by heli223** [abduallahmohamed/Social-Implicit#8]
In Table 1, the AMD/AMV are given for several models. Can you share the code about how to obtain AMD/AMV for these models, like Trajectron++?

**Comment by abduallahmohamed** [comment]
Thanks for asking. 
The code to calculate the AMD/AMV is already there. You can just save the predictions of these models which are open source. Then, use our code to calculate their AMD/AMV score. You might need to reshape the predictions to the correct shape expected by the functions.
